# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://www.kaizerpublications.com/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 'https://github.com/KaizerKrieg/KaizerPublications/'

# Title of the Site
title: Kaizer Publications
# Description of the Site
description: Your Content Marketing Solution
# URL of Image of the Site
site-image: /KaizerPublications/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Kaizer Publications, Content Marketing
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon_io(1)/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/joshua-newton-7qjqQjt7zXQ-unsplash.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kaizerpublications@gmail.com
facebook_username: dennis.kuria.5437
twitter_username: DennisK95885840
instagram_username: 
linkedin_username: dennis-kuria-2963001ab
github_username:  KaizerKrieg
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-174152438-1

# Disqus
disqus-shortname: Dennis Kuria

# Name of the Author
author-name: Dennis Kuria
# URL for the Image of the Author
author-image: /assets/images/Profpic-cropped.png
# 60 Words About the Author
author-about: Ad astra per aspera. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/dennis-kuria-2963001ab

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
